version: '3.9'
services:
  db:
    image: postgres
    container_name: "app_db"
    restart: always
    environment:
      POSTGRES_PASSWORD: Postgres2021!
      POSTGRES_USER: postgres
      POSTGRES_DB: polls
      TZ: 
    volumes:
      - "./data/postgress:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    
  web:
    container_name: "app_web"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - db
    tty: true

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
